# Generated by Django 5.1.4 on 2025-01-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_customuser_updated_comment_blogpost_comments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="likes",
        ),
    ]
