# Generated by Django 5.1.4 on 2025-01-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_savedblog"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savedblog",
            unique_together={("saved_blog", "saved_by")},
        ),
    ]
